name: Publish to npm

on:
  workflow_dispatch:
    inputs:
      dry_run:
        description: "Run build + verifiers only; skip publish"
        required: false
        type: boolean
        default: true
  push:
    tags:
      - 'v*.*.*'

permissions:
  contents: read
  id-token: write

concurrency:
  group: publish-${{ github.ref }}
  cancel-in-progress: false

jobs:
  publish:
    name: Build, test, and publish
    runs-on: ubuntu-latest
    if: github.repository == 'justrach/hri'
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 'latest'

      - name: Install dependencies (Bun)
        run: bun install --frozen-lockfile

      - name: Build package (Bun)
        run: bun run build

      - name: Verify built artifacts exist
        run: |
          test -f dist/index.js
          test -f dist/index.d.ts
          ls -la dist | sed -n '1,200p'

      - name: Verify npm pack includes dist entries
        run: |
          node -e "\
            const { spawnSync } = require('child_process');\
            const out = spawnSync('npm', ['pack', '--dry-run', '--json'], { encoding: 'utf8' });\
            if (out.status !== 0) {\
              console.error(out.stdout);\
              console.error(out.stderr);\
              process.exit(out.status || 1);\
            }\
            console.log(out.stdout);\
            const arr = JSON.parse(out.stdout);\
            const files = new Set(arr[0].files.map(f => f.path));\
            const required = ['dist/index.js','dist/index.d.ts'];\
            const missing = required.filter(p => !files.has(p));\
            if (missing.length) {\
              console.error('Missing from npm pack:', missing);\
              process.exit(1);\
            } else {\
              console.log('Pack includes required files');\
            }\
          "

      - name: Run unit tests (Bun)
        run: bun test

      - name: Dry-run publish (manual)
        if: github.event_name == 'workflow_dispatch' && inputs.dry_run == true
        run: npm publish --dry-run

      - name: Check version matches tag
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          PKG_VERSION=$(node -e "console.log(require('./package.json').version)")
          TAG_VERSION=${GITHUB_REF_NAME#v}
          if [ "$PKG_VERSION" != "$TAG_VERSION" ]; then
            echo "package.json version ($PKG_VERSION) does not match tag ($TAG_VERSION)" >&2
            exit 1
          fi

      - name: Publish to npm
        if: (github.event_name != 'workflow_dispatch' || inputs.dry_run != true) && startsWith(github.ref, 'refs/tags/')
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm publish --access public --provenance
